#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Auto-generated Isolated Integration Adapter for spatial_kinematics_external
Generated by YunYu Skills (open-source-repo-analyzer)

Implements IsolatedModuleLoader pattern:
- Avoids sys.path[0] module shadowing
- Dynamic path mounting with immediate teardown
- Type-safe parameter delegation & exception wrapping
"""

import sys
import importlib.util
from pathlib import Path
from typing import Any, Dict, Optional


class KinematicsTransformerAdapter:
    """
    Isolated Adapter bridging `spatial_kinematics_external` into the host project.
    """
    def __init__(self, repo_dir: Optional[Path] = None):
        if repo_dir is None:
            # Locate relative to workspace root
            cur = Path(__file__).resolve().parent
            while cur.parent != cur:
                if (cur / "external_repos/spatial_kinematics_external").exists():
                    break
                cur = cur.parent
            self.repo_dir = cur / "external_repos/spatial_kinematics_external"
        else:
            self.repo_dir = Path(repo_dir).resolve()

        self._instance = None
        self._validate_repo_presence()

    def _validate_repo_presence(self):
        if not self.repo_dir.exists():
            raise FileNotFoundError(f"External repo directory not found at: {self.repo_dir}")

    def _load_isolated_class(self):
        """
        Dynamically loads the target class without permanently polluting sys.path.
        Appends path temporarily and pops it immediately.
        """
        repo_str = str(self.repo_dir)
        added = False
        if repo_str not in sys.path:
            sys.path.append(repo_str)  # Append at tail, NEVER insert at 0
            added = True

        try:
            import importlib
            mod = importlib.import_module("spatial_core.transform")
            cls = getattr(mod, "KinematicsTransformer")
            return cls
        except Exception as e:
            raise ImportError(f"Failed to load 'spatial_core.transform.KinematicsTransformer' from {self.repo_dir}: {e}")
        finally:
            if added and repo_str in sys.path:
                sys.path.remove(repo_str)

    def create_instance(self, *args, **kwargs) -> Any:
        """Instantiates the underlying external class."""
        cls = self._load_isolated_class()
        self._instance = cls(*args, **kwargs)
        return self._instance

    def rotate_point(self, *args, **kwargs) -> Any:
        """Proxy execution to external method `rotate_point` with exception isolation."""
        if self._instance is None:
            self.create_instance()
        try:
            method = getattr(self._instance, "rotate_point")
            return method(*args, **kwargs)
        except Exception as e:
            raise RuntimeError(f"Error calling KinematicsTransformer.rotate_point: {e}") from e

    def translate_point(self, *args, **kwargs) -> Any:
        """Proxy execution to external method `translate_point` with exception isolation."""
        if self._instance is None:
            self.create_instance()
        try:
            method = getattr(self._instance, "translate_point")
            return method(*args, **kwargs)
        except Exception as e:
            raise RuntimeError(f"Error calling KinematicsTransformer.translate_point: {e}") from e

    def transform_full(self, *args, **kwargs) -> Any:
        """Proxy execution to external method `transform_full` with exception isolation."""
        if self._instance is None:
            self.create_instance()
        try:
            method = getattr(self._instance, "transform_full")
            return method(*args, **kwargs)
        except Exception as e:
            raise RuntimeError(f"Error calling KinematicsTransformer.transform_full: {e}") from e

