#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Demonstration of Consumer Calling External Open-Source Module via Adapter
Generated by YunYu Skills (open-source-repo-analyzer)
"""

import sys
from pathlib import Path

# Add adapter path
adapter_dir = Path(__file__).resolve().parent
if str(adapter_dir) not in sys.path:
    sys.path.insert(0, str(adapter_dir))

from golden_adapter_output import KinematicsTransformerAdapter


def main():
    print("[CONSUMER] Initializing external module adapter...")
    adapter = KinematicsTransformerAdapter()
    
    print("[CONSUMER] Invoking method: `rotate_point` via isolated adapter...")
    try:
        # Resolve Point3D dynamically
        external_dir = adapter.repo_dir
        if str(external_dir) not in sys.path:
            sys.path.append(str(external_dir))
        from spatial_core.models import Point3D
        pt = Point3D(1.0, 2.0, 3.0)
        adapter.create_instance(roll=0.0, pitch=0.0, yaw=1.5707963)
        result = adapter.rotate_point(pt)
        print(f"[CONSUMER] Execution succeeded! Rotated Point: x={result.x:.4f}, y={result.y:.4f}, z={result.z:.4f}")
    except Exception as e:
        print(f"[CONSUMER] Invocation completed with output/exception: {e}")


if __name__ == "__main__":
    main()
