#!/usr/bin/env python3
"""
scripts/gen_gbk_header.py
Generates high-performance O(1) GBK-to-Unicode Flash LUT and UTF-8 transcoder for ESP32.
"""

import codecs
import os

def main():
    dec = codecs.getdecoder('gbk')
    table = [0] * (126 * 190)
    valid_count = 0

    for h in range(0x81, 0xFF):
        h_idx = h - 0x81
        for l in range(0x40, 0xFF):
            if l == 0x7F:
                continue
            l_idx = (l - 0x40) if l <= 0x7E else (l - 0x41)
            try:
                char, _ = dec(bytes([h, l]))
                table[h_idx * 190 + l_idx] = ord(char)
                valid_count += 1
            except Exception:
                pass

    print(f"Processed GBK table: {valid_count} valid characters mapped.")

    lines = []
    lines.append("#pragma once")
    lines.append("#include <Arduino.h>")
    lines.append("#include <vector>")
    lines.append("#include <string>")
    lines.append("")
    lines.append("// Full GBK (CP936) to Unicode mapping table")
    lines.append("// 126 rows (0x81..0xFE) * 190 columns (0x40..0x7E, 0x80..0xFE) = 23940 entries (~47KB Flash)")
    lines.append("static const uint16_t GBK_TO_UNICODE_LUT[23940] PROGMEM = {")

    for i in range(0, len(table), 16):
        chunk = table[i:i+16]
        hex_vals = ", ".join(f"0x{v:04X}" for v in chunk)
        lines.append(f"    {hex_vals},")

    lines.append("};")
    lines.append("")
    lines.append("// O(1) fast lookup from GBK high/low byte to Unicode codepoint")
    lines.append("inline uint16_t gbkToUnicode(uint8_t h, uint8_t l) {")
    lines.append("    if (h < 0x81 || h > 0xFE) return 0;")
    lines.append("    int h_idx = h - 0x81;")
    lines.append("    int l_idx = -1;")
    lines.append("    if (l >= 0x40 && l <= 0x7E) {")
    lines.append("        l_idx = l - 0x40;")
    lines.append("    } else if (l >= 0x80 && l <= 0xFE) {")
    lines.append("        l_idx = l - 0x41;")
    lines.append("    }")
    lines.append("    if (l_idx < 0) return 0;")
    lines.append("    return pgm_read_word(&GBK_TO_UNICODE_LUT[h_idx * 190 + l_idx]);")
    lines.append("}")
    lines.append("")
    lines.append("// Convert 16-bit Unicode codepoint to standard UTF-8 byte sequence (1..3 bytes)")
    lines.append("inline int unicodeToUtf8(uint16_t u, uint8_t* out) {")
    lines.append("    if (u == 0) return 0;")
    lines.append("    if (u < 0x80) {")
    lines.append("        out[0] = (uint8_t)u;")
    lines.append("        return 1;")
    lines.append("    } else if (u < 0x800) {")
    lines.append("        out[0] = (uint8_t)(0xC0 | (u >> 6));")
    lines.append("        out[1] = (uint8_t)(0x80 | (u & 0x3F));")
    lines.append("        return 2;")
    lines.append("    } else {")
    lines.append("        out[0] = (uint8_t)(0xE0 | (u >> 12));")
    lines.append("        out[1] = (uint8_t)(0x80 | ((u >> 6) & 0x3F));")
    lines.append("        out[2] = (uint8_t)(0x80 | (u & 0x3F));")
    lines.append("        return 3;")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("// Strict UTF-8 validation")
    lines.append("inline bool isValidUtf8(const uint8_t* data, size_t len) {")
    lines.append("    if (data == nullptr || len == 0) return true;")
    lines.append("    size_t i = 0;")
    lines.append("    while (i < len) {")
    lines.append("        uint8_t c = data[i];")
    lines.append("        if (c < 0x80) {")
    lines.append("            i++;")
    lines.append("        } else if ((c & 0xE0) == 0xC0) {")
    lines.append("            if (i + 1 >= len) return false;")
    lines.append("            if ((data[i + 1] & 0xC0) != 0x80) return false;")
    lines.append("            if (c < 0xC2) return false; // overlong")
    lines.append("            i += 2;")
    lines.append("        } else if ((c & 0xF0) == 0xE0) {")
    lines.append("            if (i + 2 >= len) return false;")
    lines.append("            if ((data[i + 1] & 0xC0) != 0x80 || (data[i + 2] & 0xC0) != 0x80) return false;")
    lines.append("            if (c == 0xE0 && (data[i + 1] & 0xE0) == 0x80) return false; // overlong")
    lines.append("            if (c == 0xED && (data[i + 1] & 0x20) == 0x20) return false; // surrogate")
    lines.append("            i += 3;")
    lines.append("        } else if ((c & 0xF8) == 0xF0) {")
    lines.append("            if (i + 3 >= len) return false;")
    lines.append("            if ((data[i + 1] & 0xC0) != 0x80 || (data[i + 2] & 0xC0) != 0x80 || (data[i + 3] & 0xC0) != 0x80) return false;")
    lines.append("            if (c == 0xF0 && (data[i + 1] & 0x30) == 0x00) return false;")
    lines.append("            if (c > 0xF4) return false;")
    lines.append("            i += 4;")
    lines.append("        } else {")
    lines.append("            return false;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return true;")
    lines.append("}")
    lines.append("")
    lines.append("// Optional HEX-string auto-decoder (e.g. 'e4bda0' or 'e4 bd a0')")
    lines.append("inline bool tryDecodeHex(const uint8_t* data, size_t len, std::vector<uint8_t>& out_bytes) {")
    lines.append("    if (len < 4) return false;")
    lines.append("    std::string hex_str;")
    lines.append("    for (size_t i = 0; i < len; i++) {")
    lines.append("        char c = (char)data[i];")
    lines.append("        if (c == ' ' || c == '\\t' || c == '\\r' || c == '\\n' || c == ',' || c == ':') continue;")
    lines.append("        if (!isxdigit((unsigned char)c)) return false;")
    lines.append("        hex_str += c;")
    lines.append("    }")
    lines.append("    if (hex_str.length() < 4 || (hex_str.length() % 2) != 0) return false;")
    lines.append("    out_bytes.clear();")
    lines.append("    bool has_high = false;")
    lines.append("    for (size_t i = 0; i < hex_str.length(); i += 2) {")
    lines.append("        char buf[3] = { hex_str[i], hex_str[i+1], '\\0' };")
    lines.append("        uint8_t byte_val = (uint8_t)strtol(buf, nullptr, 16);")
    lines.append("        out_bytes.push_back(byte_val);")
    lines.append("        if (byte_val >= 0x80) has_high = true;")
    lines.append("    }")
    lines.append("    return has_high;")
    lines.append("}")
    lines.append("")
    lines.append("// Universal auto-detection and transcoding pipeline:")
    lines.append("// Automatically detects and handles UTF-8, GBK/GB2312, UTF-8 BOM, and Hex strings")
    lines.append("inline String sanitizeAndConvertToUtf8(const uint8_t* raw_data, size_t raw_len) {")
    lines.append("    if (raw_data == nullptr || raw_len == 0) return \"\";")
    lines.append("")
    lines.append("    // 0. Trim trailing null bytes, newlines, carriage returns")
    lines.append("    while (raw_len > 0 && (raw_data[raw_len - 1] == 0 || raw_data[raw_len - 1] == '\\r' || raw_data[raw_len - 1] == '\\n')) {")
    lines.append("        raw_len--;")
    lines.append("    }")
    lines.append("    if (raw_len == 0) return \"\";")
    lines.append("")
    lines.append("    // 1. Strip UTF-8 BOM if present")
    lines.append("    if (raw_len >= 3 && raw_data[0] == 0xEF && raw_data[1] == 0xBB && raw_data[2] == 0xBF) {")
    lines.append("        raw_data += 3;")
    lines.append("        raw_len -= 3;")
    lines.append("    }")
    lines.append("")
    lines.append("    // 2. Check if the user sent an ASCII HEX string (e.g. 'E4BDA0...' or 'E4 BD A0...')")
    lines.append("    std::vector<uint8_t> hex_bytes;")
    lines.append("    if (tryDecodeHex(raw_data, raw_len, hex_bytes)) {")
    lines.append("        return sanitizeAndConvertToUtf8(hex_bytes.data(), hex_bytes.size());")
    lines.append("    }")
    lines.append("")
    lines.append("    // 3. Check if already valid UTF-8")
    lines.append("    if (isValidUtf8(raw_data, raw_len)) {")
    lines.append("        return String((const char*)raw_data, raw_len);")
    lines.append("    }")
    lines.append("")
    lines.append("    // 4. If NOT valid UTF-8, transcode from GBK/GB2312 to UTF-8")
    lines.append("    String utf8_out = \"\";")
    lines.append("    utf8_out.reserve(raw_len * 2);")
    lines.append("")
    lines.append("    size_t i = 0;")
    lines.append("    while (i < raw_len) {")
    lines.append("        uint8_t b1 = raw_data[i];")
    lines.append("        if (b1 < 0x80) {")
    lines.append("            // Standard ASCII character")
    lines.append("            utf8_out += (char)b1;")
    lines.append("            i++;")
    lines.append("        } else if (b1 >= 0x81 && b1 <= 0xFE && (i + 1 < raw_len)) {")
    lines.append("            uint8_t b2 = raw_data[i + 1];")
    lines.append("            uint16_t unicode = gbkToUnicode(b1, b2);")
    lines.append("            if (unicode != 0) {")
    lines.append("                uint8_t utf8_buf[4] = {0};")
    lines.append("                int utf8_bytes = unicodeToUtf8(unicode, utf8_buf);")
    lines.append("                for (int k = 0; k < utf8_bytes; k++) {")
    lines.append("                    utf8_out += (char)utf8_buf[k];")
    lines.append("                }")
    lines.append("                i += 2;")
    lines.append("            } else {")
    lines.append("                utf8_out += '?';")
    lines.append("                i += 2;")
    lines.append("            }")
    lines.append("        } else {")
    lines.append("            // Stray or invalid byte")
    lines.append("            utf8_out += '?';")
    lines.append("            i++;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return utf8_out;")
    lines.append("}")
    lines.append("")

    target_path = os.path.join(os.path.dirname(__file__), "..", "firmware", "m5sticks3_buddy", "include", "gbk_to_utf8.h")
    os.makedirs(os.path.dirname(target_path), exist_ok=True)
    with open(target_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Generated {target_path} successfully ({os.path.getsize(target_path)} bytes)!")

if __name__ == "__main__":
    main()
