#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
scripts/generate_cadet_bitmaps_header.py
----------------------------------------
Converts the 135x240 binarized line art images extracted directly from the
Cadet Ren design atlas into compact 1-bit C/C++ byte arrays stored in flash
memory (PROGMEM).

Generated header:
firmware/m5sticks3_buddy/include/sticks3_cadet_bitmaps.h
"""

import os
import cv2
import numpy as np

DEV_DIR = "docs/assets/cadet_ren/device_135x240_lines"
HEADER_PATH = "firmware/m5sticks3_buddy/include/sticks3_cadet_bitmaps.h"

POSES = [
    ("bow", "CADET_BMP_BOW", "Martial Art's Bow & Salute (抱拳礼)"),
    ("horse_strike", "CADET_BMP_HORSE_STRIKE", "Horse Stance Palm Strike (扎马步冲拳)"),
    ("taichi", "CADET_BMP_TAICHI", "Flowing Tai Chi Hands (太极云手)"),
    ("dragon_punch", "CADET_BMP_DRAGON_PUNCH", "Leaping Dragon Uppercut (升龙霸天)"),
    ("wave_1", "CADET_BMP_WAVE_1", "Friendly Energetic Wave A (元气挥手A)"),
    ("wave_2", "CADET_BMP_WAVE_2", "Friendly Energetic Wave B (元气挥手B)"),
    ("front_idle", "CADET_BMP_FRONT_IDLE", "Standard Front Idle (正面待命)"),
]

def pack_image_1bit(img_path):
    img = cv2.imread(img_path, 0)
    if img is None:
        raise FileNotFoundError(f"Missing {img_path}")
    h, w = img.shape
    row_bytes = (w + 7) // 8 # 17 bytes for 135px
    packed = bytearray(row_bytes * h)

    for y in range(h):
        for x in range(w):
            if img[y, x] > 80:
                byte_idx = y * row_bytes + (x >> 3)
                bit_idx = 7 - (x & 7)
                packed[byte_idx] |= (1 << bit_idx)

    return packed, w, h, row_bytes

def generate_header():
    lines = [
        "// ============================================================================",
        "// sticks3_cadet_bitmaps.h",
        "// Authentic 1:1 Binarized Line Art Bitmaps extracted from Cadet Ren Design Atlas",
        "// Automatically generated by scripts/generate_cadet_bitmaps_header.py",
        "// DO NOT MODIFY DIRECTLY",
        "// ============================================================================",
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "#include \"sticks3_bear_kinematics.h\"",
        "#include <M5GFX.h>",
        "",
        "namespace sticks3 {",
        "",
        "// Screen Dimensions for Bitmaps",
        "static constexpr int CADET_BMP_W = 135;",
        "static constexpr int CADET_BMP_H = 240;",
        "static constexpr int CADET_BMP_ROW_BYTES = 17;",
        "static constexpr int CADET_BMP_SIZE = CADET_BMP_ROW_BYTES * CADET_BMP_H; // 4080 bytes",
        "",
        "// Theme Colors for Atlas Line Art Rendering",
        "static constexpr uint16_t CADET_LINE_IVORY = 0xFFDE; // Warm Ivory White #FEF3C7 (RGB565)",
        "static constexpr uint16_t CADET_LINE_GOLD  = 0xFDE0; // Imperial Gold #F59E0B (RGB565)",
        "static constexpr uint16_t CADET_BG_OBSIDIAN = 0x0862; // Midnight Obsidian #0B0F19 (RGB565)",
        "",
    ]

    for name, c_name, desc in POSES:
        img_path = os.path.join(DEV_DIR, f"{name}_135x240.png")
        packed, w, h, row_bytes = pack_image_1bit(img_path)
        lines.append(f"// {desc} - {len(packed)} bytes")
        lines.append(f"static const uint8_t {c_name}[{len(packed)}] PROGMEM = {{")
        
        # Format 16 bytes per line
        for i in range(0, len(packed), 16):
            chunk = packed[i:i+16]
            hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
            if i + 16 < len(packed):
                lines.append(f"    {hex_str},")
            else:
                lines.append(f"    {hex_str}")
        lines.append("};")
        lines.append("")

    # Helper function to get bitmap for an action
    lines.extend([
        "/**",
        " * @brief Resolves authentic atlas bitmap for a given action and animation frame.",
        " */",
        "inline const uint8_t* getCadetAtlasBitmap(BearAction act, int frame) {",
        "    switch (act) {",
        "        case BEAR_ACT_KUNGFU:        return CADET_BMP_HORSE_STRIKE;",
        "        case BEAR_ACT_TAICHI:        return CADET_BMP_TAICHI;",
        "        case BEAR_ACT_DRAGON_PUNCH:  return CADET_BMP_DRAGON_PUNCH;",
        "        case BEAR_ACT_BOW:           return CADET_BMP_BOW;",
        "        case BEAR_ACT_WAVE:          return (frame % 2 == 0) ? CADET_BMP_WAVE_1 : CADET_BMP_WAVE_2;",
        "        case BEAR_ACT_IDLE:          return CADET_BMP_FRONT_IDLE;",
        "        default:                     return nullptr;",
        "    }",
        "}",
        "",
        "/**",
        " * @brief High-speed zero-copy 1-bit bitmap renderer to LGFX_Sprite with optional kinematics offset.",
        " */",
        "inline void drawCadetAtlasLineart(LovyanGFX& d, const uint8_t* bmp, uint16_t color = CADET_LINE_IVORY, int dx = 0, int dy = 0) {",
        "    if (!bmp) return;",
        "    for (int y = 20; y < 218; y++) {",
        "        int dst_y = y + dy;",
        "        if (dst_y < 19 || dst_y >= 218) continue;",
        "        const uint8_t* row = bmp + (y * CADET_BMP_ROW_BYTES);",
        "        for (int x = 0; x < CADET_BMP_W; x++) {",
        "            if ((row[x >> 3] >> (7 - (x & 7))) & 1) {",
        "                int dst_x = x + dx;",
        "                if (dst_x >= 0 && dst_x < CADET_BMP_W) {",
        "                    d.drawPixel(dst_x, dst_y, color);",
        "                }",
        "            }",
        "        }",
        "    }",
        "}",
        "",
        "} // namespace sticks3",
    ])

    content = "\n".join(lines) + "\n"
    os.makedirs(os.path.dirname(HEADER_PATH), exist_ok=True)
    with open(HEADER_PATH, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Header successfully generated at {HEADER_PATH} ({len(content)} bytes)")

if __name__ == '__main__':
    generate_header()
