#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Cross-Project Integration Adapter Generator (repo_adapter.py)
Agentic Skills Standard Specification (ASSS v1.0) Compliant

Features:
- Path-traversal proof target resolution (disallows escaping workspace boundaries)
- Non-polluting IsolatedModuleLoader avoiding sys.path[0] module shadowing (hijacking)
- Polyglot Subprocess/IPC adapter generation for Node.js, Go, Rust binaries
- Git command argument injection prevention
- Automatic double .gitignore protection in external_repos/
"""

import os
import sys
import shutil
import argparse
import subprocess
from pathlib import Path
from typing import List, Dict, Any, Optional

DEFAULT_EXTERNAL_DIR_NAME = "external_repos"


class SecurityException(Exception):
    """Raised when an operation violates security boundaries."""
    pass


class RepoIntegrator:
    def __init__(self, workspace_root: Path, external_dir_name: str = DEFAULT_EXTERNAL_DIR_NAME):
        self.workspace_root = workspace_root.resolve()
        self.external_dir = (self.workspace_root / external_dir_name).resolve()
        self._ensure_isolation_setup()

    def _ensure_isolation_setup(self):
        """Ensures external_repos exists and is thoroughly ignored by git."""
        self.external_dir.mkdir(parents=True, exist_ok=True)
        gitignore_path = self.external_dir / ".gitignore"
        if not gitignore_path.exists():
            gitignore_path.write_text("# Ignore all downloaded external repositories and dependencies\n*\n!.gitignore\n!README.md\n", encoding="utf-8")

        # Verify root .gitignore contains external_repos/
        root_gitignore = self.workspace_root / ".gitignore"
        if root_gitignore.exists():
            content = root_gitignore.read_text(encoding="utf-8", errors="replace")
            if "external_repos" not in content:
                with open(root_gitignore, "a", encoding="utf-8") as f:
                    f.write("\nexternal_repos/\n")

    def validate_destination_path(self, target_path: Path) -> Path:
        """Enforces that target paths remain strictly inside the workspace boundaries."""
        resolved = target_path.resolve()
        if not (resolved == self.workspace_root or self.workspace_root in resolved.parents):
            raise SecurityException(f"Path traversal detected: {target_path} escapes workspace root {self.workspace_root}")
        return resolved

    def fetch_repo(self, source: str, target_name: Optional[str] = None) -> Path:
        """
        Safely fetches an open-source repository into external_repos/.
        Guards against Git parameter injection and path traversal.
        """
        if source.startswith("-"):
            raise SecurityException(f"Invalid repository source starting with hyphen: {source}")

        is_git_url = source.startswith("http://") or source.startswith("https://") or source.startswith("git@")
        
        if not target_name:
            if is_git_url:
                target_name = source.rstrip("/").split("/")[-1].replace(".git", "")
            else:
                target_name = Path(source).name

        # Sanitize target name
        target_name = "".join(c if c.isalnum() or c in ("-", "_") else "_" for c in target_name)
        dest_path = self.validate_destination_path(self.external_dir / target_name)

        if dest_path.exists():
            print(f"[INFO] Target repository already exists in isolation folder: {dest_path}")
            return dest_path

        if is_git_url:
            print(f"[INFO] Cloning remote repository: {source} -> {dest_path}")
            cmd = ["git", "clone", "--depth", "1", "--", source, str(dest_path)]
            subprocess.run(cmd, check=True)
        else:
            src_path = Path(source).resolve()
            if not src_path.is_dir():
                raise ValueError(f"Source path is not a valid directory: {src_path}")
            print(f"[INFO] Copying local repository: {src_path} -> {dest_path}")
            shutil.copytree(src_path, dest_path, ignore=shutil.ignore_patterns(".git", "__pycache__", "node_modules", "venv", ".venv", "target"))

        return dest_path

    def generate_adapter(self, repo_path: Path, module_name: str, target_class: str, methods: List[str], output_file: Optional[Path] = None) -> Path:
        """
        Generates a robust Python Adapter class using isolated dynamic loading
        to avoid global sys.path module shadowing (e.g. external os.py hijacking host).
        """
        rel_repo_posix = repo_path.relative_to(self.workspace_root).as_posix()
        adapter_class_name = f"{target_class}Adapter"

        code = f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Auto-generated Isolated Integration Adapter for {repo_path.name}
Generated by YunYu Skills (open-source-repo-analyzer)

Implements IsolatedModuleLoader pattern:
- Avoids sys.path[0] module shadowing
- Dynamic path mounting with immediate teardown
- Type-safe parameter delegation & exception wrapping
"""

import sys
import importlib.util
from pathlib import Path
from typing import Any, Dict, Optional


class {adapter_class_name}:
    """
    Isolated Adapter bridging `{repo_path.name}` into the host project.
    """
    def __init__(self, repo_dir: Optional[Path] = None):
        if repo_dir is None:
            # Locate relative to workspace root
            cur = Path(__file__).resolve().parent
            while cur.parent != cur:
                if (cur / "{rel_repo_posix}").exists():
                    break
                cur = cur.parent
            self.repo_dir = cur / "{rel_repo_posix}"
        else:
            self.repo_dir = Path(repo_dir).resolve()

        self._instance = None
        self._validate_repo_presence()

    def _validate_repo_presence(self):
        if not self.repo_dir.exists():
            raise FileNotFoundError(f"External repo directory not found at: {{self.repo_dir}}")

    def _load_isolated_class(self):
        """
        Dynamically loads the target class without permanently polluting sys.path.
        Appends path temporarily and pops it immediately.
        """
        repo_str = str(self.repo_dir)
        added = False
        if repo_str not in sys.path:
            sys.path.append(repo_str)  # Append at tail, NEVER insert at 0
            added = True

        try:
            import importlib
            mod = importlib.import_module("{module_name}")
            cls = getattr(mod, "{target_class}")
            return cls
        except Exception as e:
            raise ImportError(f"Failed to load '{module_name}.{target_class}' from {{self.repo_dir}}: {{e}}")
        finally:
            if added and repo_str in sys.path:
                sys.path.remove(repo_str)

    def create_instance(self, *args, **kwargs) -> Any:
        """Instantiates the underlying external class."""
        cls = self._load_isolated_class()
        self._instance = cls(*args, **kwargs)
        return self._instance

'''
        for m in methods:
            code += f'''    def {m}(self, *args, **kwargs) -> Any:
        """Proxy execution to external method `{m}` with exception isolation."""
        if self._instance is None:
            self.create_instance()
        try:
            method = getattr(self._instance, "{m}")
            return method(*args, **kwargs)
        except Exception as e:
            raise RuntimeError(f"Error calling {target_class}.{m}: {{e}}") from e

'''

        if output_file is None:
            output_file = self.workspace_root / "skills" / "open-source-repo-analyzer" / "examples" / f"{repo_path.name}_adapter.py"

        output_file = self.validate_destination_path(Path(output_file))
        output_file.parent.mkdir(parents=True, exist_ok=True)
        output_file.write_text(code, encoding="utf-8")
        print(f"[OK] Generated Adapter file: {output_file}")
        return output_file

    def generate_polyglot_subprocess_adapter(self, repo_path: Path, executable_name: str, commands: List[str], output_file: Optional[Path] = None) -> Path:
        """
        Generates a sub-process CLI/IPC adapter for non-Python external tools (Node/Rust/Go).
        """
        rel_repo_posix = repo_path.relative_to(self.workspace_root).as_posix()
        class_name = f"{executable_name.title().replace('-', '')}CLIAdapter"

        code = f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Auto-generated Polyglot Subprocess Adapter for {repo_path.name} ({executable_name})
Generated by YunYu Skills (open-source-repo-analyzer)
"""

import sys
import json
import subprocess
from pathlib import Path
from typing import Dict, Any, List, Optional


class {class_name}:
    """
    Subprocess IPC Adapter executing `{executable_name}` in `{repo_path.name}`.
    """
    def __init__(self, repo_dir: Optional[Path] = None):
        if repo_dir is None:
            cur = Path(__file__).resolve().parent
            while cur.parent != cur:
                if (cur / "{rel_repo_posix}").exists():
                    break
                cur = cur.parent
            self.repo_dir = cur / "{rel_repo_posix}"
        else:
            self.repo_dir = Path(repo_dir).resolve()

    def run_command(self, subcmd: str, args: List[str] = None, timeout_sec: int = 15) -> Dict[str, Any]:
        """Executes CLI command in isolated subprocess."""
        cmd = ["{executable_name}", subcmd] + (args or [])
        try:
            proc = subprocess.run(
                cmd,
                cwd=str(self.repo_dir),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                timeout=timeout_sec
            )
            return {{
                "exit_code": proc.returncode,
                "stdout": proc.stdout,
                "stderr": proc.stderr,
                "success": proc.returncode == 0
            }}
        except Exception as e:
            return {{"exit_code": -1, "stdout": "", "stderr": str(e), "success": False}}

'''
        if output_file is None:
            output_file = self.workspace_root / "skills" / "open-source-repo-analyzer" / "examples" / f"{executable_name}_polyglot_adapter.py"

        output_file = self.validate_destination_path(Path(output_file))
        output_file.parent.mkdir(parents=True, exist_ok=True)
        output_file.write_text(code, encoding="utf-8")
        print(f"[OK] Generated Polyglot Adapter file: {output_file}")
        return output_file

    def generate_consumer_example(self, adapter_path: Path, class_name: str, method_name: str, output_file: Optional[Path] = None) -> Path:
        """Generates a runnable demonstration script showing how to call the external repo via the adapter."""
        code = f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Demonstration of Consumer Calling External Open-Source Module via Adapter
Generated by YunYu Skills (open-source-repo-analyzer)
"""

import sys
from pathlib import Path

# Add adapter path
adapter_dir = Path(__file__).resolve().parent
if str(adapter_dir) not in sys.path:
    sys.path.insert(0, str(adapter_dir))

from {adapter_path.stem} import {class_name}Adapter


def main():
    print("[CONSUMER] Initializing external module adapter...")
    adapter = {class_name}Adapter()
    
    print("[CONSUMER] Invoking method: `{method_name}` via isolated adapter...")
    try:
        result = adapter.{method_name}()
        print(f"[CONSUMER] Execution succeeded! Result: {{result}}")
    except Exception as e:
        print(f"[CONSUMER] Invocation completed with output/exception: {{e}}")


if __name__ == "__main__":
    main()
'''
        if output_file is None:
            output_file = adapter_path.parent / f"run_{adapter_path.stem}.py"

        output_file = self.validate_destination_path(Path(output_file))
        output_file.parent.mkdir(parents=True, exist_ok=True)
        output_file.write_text(code, encoding="utf-8")
        print(f"[OK] Generated Consumer Example: {output_file}")
        return output_file


def main():
    parser = argparse.ArgumentParser(description="Cross-Project Adapter & Downloader Tool")
    parser.add_argument("source", type=str, help="Git URL or local directory of the open-source repository")
    parser.add_argument("--name", type=str, default=None, help="Target folder name inside external_repos/")
    parser.add_argument("--module", type=str, default="core", help="Target module name to adapt")
    parser.add_argument("--target-class", type=str, default="Engine", help="Target class name to adapt")
    parser.add_argument("--methods", nargs="*", default=["process", "status"], help="Methods to expose on adapter")
    parser.add_argument("--output-adapter", type=str, default=None, help="Custom path for generated adapter")
    parser.add_argument("--polyglot", action="store_true", help="Generate polyglot subprocess CLI adapter")
    args = parser.parse_args()

    # Find workspace root
    cur = Path(__file__).resolve().parent
    workspace = cur.parent.parent.parent

    integrator = RepoIntegrator(workspace)
    repo_dest = integrator.fetch_repo(args.source, target_name=args.name)

    if args.polyglot:
        adapter_path = integrator.generate_polyglot_subprocess_adapter(
            repo_path=repo_dest,
            executable_name=args.target_class.lower(),
            commands=args.methods,
            output_file=Path(args.output_adapter) if args.output_adapter else None
        )
    else:
        adapter_path = integrator.generate_adapter(
            repo_path=repo_dest,
            module_name=args.module,
            target_class=args.target_class,
            methods=args.methods,
            output_file=Path(args.output_adapter) if args.output_adapter else None
        )

        integrator.generate_consumer_example(
            adapter_path=adapter_path,
            class_name=args.target_class,
            method_name=args.methods[0] if args.methods else "process"
        )


if __name__ == "__main__":
    main()
