#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Auto-generated Isolated Integration Adapter for mini_bdx_runtime
Generated by YunYu Skills (open-source-repo-analyzer)

Implements IsolatedModuleLoader pattern:
- Direct spec_from_file_location loading without triggering package __init__
- Non-polluting sys.path isolation
- Safe exception handling
"""

import sys
import os
import importlib.util
from pathlib import Path
from typing import Any, Dict, Optional


class DuckConfigAdapter:
    """
    Isolated Adapter bridging `mini_bdx_runtime.duck_config.DuckConfig` into the host project.
    Directly binds to duck_config.py without importing onnxruntime or rustypot.
    """
    def __init__(self, config_json_path: Optional[str] = None, ignore_default: bool = True, repo_dir: Optional[Path] = None):
        if repo_dir is None:
            cur = Path(__file__).resolve().parent
            while cur.parent != cur:
                candidate = cur / "Open_Duck_Mini_Runtime/mini_bdx_runtime/mini_bdx_runtime"
                if candidate.exists():
                    self.repo_dir = candidate
                    break
                candidate2 = cur / "microduck/Open_Duck_Mini_Runtime/mini_bdx_runtime/mini_bdx_runtime"
                if candidate2.exists():
                    self.repo_dir = candidate2
                    break
                cur = cur.parent
            else:
                self.repo_dir = Path("D:/workspace/code/yunyu-esp32/microduck/Open_Duck_Mini_Runtime/mini_bdx_runtime/mini_bdx_runtime")
        else:
            self.repo_dir = Path(repo_dir).resolve()

        self._validate_repo_presence()
        self._instance = None
        self._load_and_init(config_json_path=config_json_path, ignore_default=ignore_default)

    def _validate_repo_presence(self):
        target_file = self.repo_dir / "duck_config.py"
        if not target_file.exists():
            raise FileNotFoundError(f"duck_config.py not found at: {target_file}")

    def _load_isolated_class(self):
        """
        Dynamically loads DuckConfig directly from source file without package __init__.
        """
        target_file = self.repo_dir / "duck_config.py"
        try:
            spec = importlib.util.spec_from_file_location("isolated_duck_config", str(target_file))
            if spec is None or spec.loader is None:
                raise ImportError(f"Cannot create spec for {target_file}")
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            return getattr(mod, "DuckConfig")
        except Exception as e:
            raise ImportError(f"Failed to load 'DuckConfig' from {target_file}: {e}")

    def _load_and_init(self, config_json_path: Optional[str] = None, ignore_default: bool = True):
        cls = self._load_isolated_class()
        self._instance = cls(config_json_path=config_json_path, ignore_default=ignore_default)

    @property
    def joints_offset(self) -> Dict[str, float]:
        return self._instance.joints_offset

    @property
    def imu_upside_down(self) -> bool:
        return self._instance.imu_upside_down

    @property
    def start_paused(self) -> bool:
        return self._instance.start_paused

    @property
    def phase_frequency_factor_offset(self) -> float:
        return self._instance.phase_frequency_factor_offset

    def get_raw_instance(self) -> Any:
        return self._instance


if __name__ == "__main__":
    adapter = DuckConfigAdapter(ignore_default=True)
    print("[OK] Successfully loaded DuckConfig via isolated adapter!")
    print(f"Total joint offsets loaded: {len(adapter.joints_offset)}")
    for k, v in list(adapter.joints_offset.items())[:5]:
        print(f"  - {k}: {v:.4f} rad")
