#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Microduck 61-D Observation Vector & Action Adapter
Generated by YunYu Skills (open-source-repo-analyzer)

Provides pure Python reference implementation of:
1. 61-D Observation Vector Builder (matching duck-control/src/obs.rs)
2. 14-D Action to Joint Angles Converter
3. Joint Ordering and ID Mappings (15 joints total, mouth at index 9)
"""

import math
import numpy as np
from typing import List, Dict, Tuple, Optional

# Constants matching duck-control/src/obs.rs and model.rs
OBS_LEN = 61
ACTION_LEN = 14
NUM_JOINTS = 15
MOUTH_INDEX = 9
ACTION_SCALE = 0.25

JOINT_NAMES = [
    "left_hip_yaw",    # 0, id 20
    "left_hip_roll",   # 1, id 21
    "left_hip_pitch",  # 2, id 22
    "left_knee",       # 3, id 23
    "left_ankle",      # 4, id 24
    "neck_pitch",      # 5, id 30
    "head_pitch",      # 6, id 31
    "head_yaw",        # 7, id 32
    "head_roll",       # 8, id 33
    "mouth",           # 9, id 34 (excluded from policy)
    "right_hip_yaw",   # 10, id 10
    "right_hip_roll",  # 11, id 11
    "right_hip_pitch", # 12, id 12
    "right_knee",      # 13, id 13
    "right_ankle",     # 14, id 14
]

DEFAULT_HOME_POSITION = [
    0.0,     # left_hip_yaw
    -0.0873, # left_hip_roll
    -0.4579, # left_hip_pitch
    -0.0049, # left_knee
    0.4530,  # left_ankle
    0.3491,  # neck_pitch
    0.3491,  # head_pitch
    0.0,     # head_yaw
    0.0,     # head_roll
    0.0,     # mouth
    0.0,     # right_hip_yaw
    0.0873,  # right_hip_roll
    0.4579,  # right_hip_pitch
    0.0049,  # right_knee
    -0.4530, # right_ankle
]


class MicroduckObservationBuilder:
    """
    Constructs the exact 61-D float32 observation vector consumed by the RL policy.
    """
    def __init__(self):
        self.home_pos = np.array(DEFAULT_HOME_POSITION, dtype=np.float32)
        # 14 active joint home positions (excluding mouth)
        self.active_home_pos = np.delete(self.home_pos, MOUTH_INDEX)
        self.last_action = np.zeros(ACTION_LEN, dtype=np.float32)

    def build_observation(
        self,
        gyro: List[float],                 # [gx, gy, gz] in rad/s (trunk frame)
        projected_gravity: List[float],    # [gx, gy, gz] unit vector in trunk frame
        joint_positions_15: List[float],   # 15 joint current positions in rad
        joint_velocities_15: List[float],  # 15 joint current velocities in rad/s
        cmd_vel: List[float] = [0.0, 0.0, 0.0],          # [vx, vy, vyaw]
        cmd_head: List[float] = [0.0, 0.0, 0.0, 0.0],     # [neck_pitch, head_pitch, head_yaw, head_roll]
        cmd_body_z: float = 0.0,
        cmd_body_roll: float = 0.0,
        cmd_body_pitch: float = 0.0
    ) -> np.ndarray:
        """
        Builds and validates the 61-D flat observation array.
        """
        pos_15 = np.array(joint_positions_15, dtype=np.float32)
        vel_15 = np.array(joint_velocities_15, dtype=np.float32)

        # Remove mouth joint at index 9
        pos_14 = np.delete(pos_15, MOUTH_INDEX)
        vel_14 = np.delete(vel_15, MOUTH_INDEX)

        # 0..3: gyro (3)
        # 3..6: projected gravity (3)
        # 6..20: joint pos minus home (14)
        # 20..34: joint vel (14)
        # 34..48: previous action (14)
        # 48..61: command block (13)
        pos_delta_14 = pos_14 - self.active_home_pos

        cmd_block = np.zeros(13, dtype=np.float32)
        cmd_block[0:3] = cmd_vel[:3]               # vx, vy, vyaw
        cmd_block[3:7] = cmd_head[:4]              # head deltas
        cmd_block[7:9] = 0.0                       # body x, y (always 0)
        cmd_block[9] = cmd_body_z                  # body z
        cmd_block[10] = cmd_body_roll              # body roll
        cmd_block[11] = cmd_body_pitch             # body pitch
        cmd_block[12] = 0.0                        # body yaw (always 0)

        obs = np.concatenate([
            np.array(gyro[:3], dtype=np.float32),
            np.array(projected_gravity[:3], dtype=np.float32),
            pos_delta_14,
            vel_14,
            self.last_action,
            cmd_block
        ])

        assert len(obs) == OBS_LEN, f"Expected obs len {OBS_LEN}, got {len(obs)}"
        return obs

    def action_to_joint_targets(self, action_14: np.ndarray, mouth_open: float = 0.0) -> np.ndarray:
        """
        Converts 14-D policy action to 15-D absolute joint targets (rad).
        Updates internal last_action cache.
        """
        action = np.array(action_14, dtype=np.float32)
        assert len(action) == ACTION_LEN, f"Expected action len {ACTION_LEN}, got {len(action)}"
        self.last_action = action.copy()

        # Target = Home + Action * Scale
        targets_14 = self.active_home_pos + action * ACTION_SCALE

        # Insert mouth target at index 9
        mouth_closed = -5.0 * math.pi / 180.0
        mouth_max = 30.0 * math.pi / 180.0
        mouth_target = mouth_closed + np.clip(mouth_open, 0.0, 1.0) * (mouth_max - mouth_closed)

        targets_15 = np.insert(targets_14, MOUTH_INDEX, mouth_target)
        return targets_15


if __name__ == "__main__":
    builder = MicroduckObservationBuilder()
    dummy_gyro = [0.01, -0.02, 0.0]
    dummy_grav = [0.0, 0.0, -1.0] # Flat gravity vector
    dummy_pos = DEFAULT_HOME_POSITION
    dummy_vel = [0.0] * NUM_JOINTS

    obs = builder.build_observation(
        gyro=dummy_gyro,
        projected_gravity=dummy_grav,
        joint_positions_15=dummy_pos,
        joint_velocities_15=dummy_vel,
        cmd_vel=[0.2, 0.0, 0.0] # Command 0.2 m/s forward
    )
    print("[OK] Successfully generated 61-D observation vector!")
    print(f"Observation Shape: {obs.shape} | Data Type: {obs.dtype}")
    print(f"Sample values (gyro + grav + delta): {obs[:10]}")

    # Simulated action output from RL policy
    dummy_action = np.random.uniform(-0.5, 0.5, size=14).astype(np.float32)
    targets = builder.action_to_joint_targets(dummy_action, mouth_open=0.5)
    print(f"[OK] Successfully computed 15 joint targets (rad)!")
    print(f"Target count: {len(targets)} | Mouth angle: {targets[MOUTH_INDEX]:.4f} rad")
