#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Auto-generated Polyglot Subprocess Adapter for microduck (robotctl)
Generated by YunYu Skills (open-source-repo-analyzer)
"""

import sys
import json
import subprocess
from pathlib import Path
from typing import Dict, Any, List, Optional


class RobotctlCLIAdapter:
    """
    Subprocess IPC Adapter executing `robotctl` in `microduck`.
    """
    def __init__(self, repo_dir: Optional[Path] = None):
        if repo_dir is None:
            cur = Path(__file__).resolve().parent
            while cur.parent != cur:
                if (cur / "microduck/microduck").exists():
                    break
                cur = cur.parent
            self.repo_dir = cur / "microduck/microduck"
        else:
            self.repo_dir = Path(repo_dir).resolve()

    def run_command(self, subcmd: str, args: List[str] = None, timeout_sec: int = 15) -> Dict[str, Any]:
        """Executes CLI command in isolated subprocess."""
        cmd = ["robotctl", subcmd] + (args or [])
        try:
            proc = subprocess.run(
                cmd,
                cwd=str(self.repo_dir),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                timeout=timeout_sec
            )
            return {
                "exit_code": proc.returncode,
                "stdout": proc.stdout,
                "stderr": proc.stderr,
                "success": proc.returncode == 0
            }
        except Exception as e:
            return {"exit_code": -1, "stdout": "", "stderr": str(e), "success": False}

